import java.util.Scanner;

public class LaunchException {
	public static void main(String[] args) {
		try {
			System.out.println("Division Operation");
			Scanner sc = new Scanner(System.in);
			System.out.println("Enter the Numerator: ");
			int num = sc.nextInt();//critical statement ----> input mismatch exception
			System.out.println("Enter the denominator: ");
			int den = sc.nextInt();//critical statement ----> input mismatch exception
			int res = num/den;//critical statement ----> arithmetic exception
			System.out.println(res);
			
			System.out.println("Array Operation");
			
		}
		catch (Exception e) {
			System.out.println("Exception Handled in Main");
		}
	}
}
